services:
    # <helper>
    encore_merchant.helper.authentication:
        class: Encore\MerchantBundle\Helper\AuthenticationHelper
        arguments:
            - @security.context
            - @doctrine.orm.entity_manager
    # </helper>
