encore_merchant:
    resource: "@EncoreMerchantBundle/Resources/config/routing.yml"
    prefix:   /

encore_customer:
    resource: "@EncoreCustomerBundle/Resources/config/routing.yml"
    prefix:   /

