encore_merchant:
    resource: "@EncoreMerchantBundle/Controller"
    host:     "%encore.host.merchant%"
    prefix:   "%encore.route_prefix.merchant%"

encore:
    resource: "@EncoreCustomerBundle/Resources/config/routing.yml"
    host:       "%encore.host.main%"
    prefix:     "%encore.route_prefix.customer%"
    options:
        expose: true
