services:
        encore.customer.request_matcher:
            class: Symfony\Component\HttpFoundation\RequestMatcher
            arguments: [ "%encore.route_prefix.customer%", "%encore.host.main%" ]
        encore.merchant.request_matcher:
            class: Symfony\Component\HttpFoundation\RequestMatcher
            arguments: [ "%encore.route_prefix.merchant%", "%encore.host.merchant%" ]

jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_NORMAL:      ROLE_USER
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_ADMIN_USER
        ROLE_MERCHANT:
            - ROLE_ADMIN
        ROLE_EDITOR:
            - ROLE_ADMIN
            - ROLE_MERCHANT
        ROLE_SUPER_ADMIN:
            - ROLE_EDITOR
            - ROLE_ADMIN_USER_ROLES
            - ROLE_ADMIN_MERCHANT
            - ROLE_ALLOWED_TO_SWITCH

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js)/
                security: false
        customer:
            pattern: "%encore.route_prefix.customer%/.*"
#            request_matcher: encore.customer.request_matcher
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path:                         "%encore.route_prefix.customer%/login"
                use_forward:                        false
                check_path:                         "%encore.route_prefix.customer%/login_check"
                failure_path:                       "%encore.route_prefix.customer%/login"
                use_referer:                        true
                default_target_path:                "%encore.route_prefix.customer%/"
                always_use_default_target_path:     false
                username_parameter:                 _username
                password_parameter:                 _password
            context:    encore_auth
            logout:
                path:                             "%encore.route_prefix.customer%/logout"
                target:                           "%encore.route_prefix.customer%/"
            anonymous:    true
        merchant:
            pattern: "%encore.route_prefix.customer%/.*"
#            request_matcher: encore.merchant.request_matcher
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path:                         "%encore.route_prefix.merchant%/login"
                use_forward:                        false
                check_path:                         "%encore.route_prefix.merchant%/login_check"
                failure_path:                       "%encore.route_prefix.merchant%/login"
                use_referer:                        true
                default_target_path:                "%encore.route_prefix.merchant%/"
                always_use_default_target_path:     false
                username_parameter:                 _username
                password_parameter:                 _password
            context:    encore_auth
            logout:
                path:                             "%encore.route_prefix.merchant%/logout"
                target:                           "%encore.route_prefix.merchant%/"
            anonymous:    true
    access_control:
        - { path: "^%encore.route_prefix.customer%/login$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%encore.route_prefix.customer%/logout$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%encore.route_prefix.customer%/login-check$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%encore.route_prefix.customer%/forgot-password$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%encore.route_prefix.customer%/reset-password$", role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: "^%encore.route_prefix.merchant%/login$", roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: "^%encore.route_prefix.merchant%/logout$", roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_USER] }
        - { path: "^%encore.route_prefix.merchant%/login-check$", roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: "^%encore.route_prefix.merchant%", roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_MERCHANT] }

        - { path: "^%encore.route_prefix.customer%", host: "%encore.host.main%", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%encore.route_prefix.merchant%", host: "%encore.host.main%", role: IS_AUTHENTICATED_ANONYMOUSLY }
