# <parameters>
parameters:
  # URI prefixes
  encore.uri_prefix.event:
      "/images/data/events"
  encore.uri_prefix.user:
      "/images/data/user-avatar"
# </parameters>

vich_uploader:
    db_driver: orm
    mappings:
        event_image:
            uri_prefix: %encore.uri_prefix.event%
            upload_destination: %kernel.root_dir%/../web/images/data/events
            namer: encore.file_namer.uuid_namer
            delete_on_remove: false
            delete_on_update: false
            inject_on_load: false