<?php

namespace Encore\CustomerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderRepository extends EntityRepository
{
}
