<?php

namespace Encore\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventSeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventSeatRepository extends EntityRepository
{
}
