<?php

namespace Encore\CustomerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventSectionRepository extends EntityRepository
{
}
