encore_customer_welcome:
  pattern:  /
  defaults: { _controller: EncoreCustomerBundle:Welcome:index }

encore_customer_login:
    pattern:  /login
    defaults: { _controller: EncoreCustomerBundle:Login:index }

