encore_customer_welcome:
  resource: "@EncoreCustomerBundle/Controller/HomeController.php"
  type:     annotation

encore_static:
  resource:  "@EncoreCustomerBundle/Controller/StaticController.php"
  type:     annotation
  prefix:   /

encore_complete_profile:
  resource:  "@EncoreCustomerBundle/Controller/ProfileController.php"
  type:     annotation
  prefix:   /

encore_edit_profile:
  resource:  "@EncoreCustomerBundle/Controller/ProfileController.php"
  type:     annotation
  prefix:   /

encore_event:
  resource:  "@EncoreCustomerBundle/Controller/EventController.php"
  type:     annotation

encore_seat_selection:
  resource:  "@EncoreCustomerBundle/Controller/SeatSelectionController.php"
  type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    path:     /password/change
    defaults: { _controller: "FOSUserBundle:ChangePassword:changePassword" }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

encore_authentication:
  resource: "@EncoreCustomerBundle/Controller/AuthenticationController.php"
  type:     annotation
