encore_customer_welcome:
  pattern:  /
  defaults: { _controller: EncoreCustomerBundle:Welcome:index }

encore_registration_success:
  pattern:  /completeinformation
  defaults: {_controller: EncoreCustomerBundle:RegistrationSuccess:show }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    # /login, /check, /logout

fos_user_change_password:
    path:     /password/change
    defaults: { _controller: "FOSUserBundle:ChangePassword:changePassword" }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_register:
    resource: "@FOSUserBundle//Resources/config/routing/registration.xml"
    prefix: /signup