parameters:
#    encore_customer.example.class: Encore\CustomerBundle\Example

services:
#    encore_customer.example:
#        class: %encore_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     encore.user_manager:
        class: Encore\CustomerBundle\Services\EncoreUserManager
        arguments:
          - @doctrine.orm.entity_manager
          - @security.context
     encore.registration_success:
        class: Encore\CustomerBundle\EventListener\RegistrationSuccessListener
        arguments: [@router]
        tags:
          - { name: kernel.event_subscriber }
     encore.event_manager:
        class: Encore\CustomerBundle\Model\EventManager
        arguments:
          - @doctrine.orm.entity_manager
     encore.form.type.user_profile:
        class: Encore\CustomerBundle\Form\Type\UserProfileType
        tags:
          - { name: form.type, alias: user_profile }

     encore.encore_search:
        class: Encore\CustomerBundle\Services\EncoreSearch
        arguments:
          - @doctrine.orm.entity_manager
          - @request
        scope:  request

     encore.file_namer.uuid_namer:
        class: Encore\CustomerBundle\VichUploader\Naming\UuidNamer
