parameters:
#    encore_customer.example.class: Encore\CustomerBundle\Example

services:
#    encore_customer.example:
#        class: %encore_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     encore.user_manager:
        class: Encore\CustomerBundle\Services\EncoreUserManager
        arguments:
          - @doctrine.orm.entity_manager
          - @security.context