parameters:
#    encore_customer.example.class: Encore\CustomerBundle\Example

services:
#    encore_customer.example:
#        class: %encore_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
